#! /bin/sh

CGL_DIR=/tmp/${USER}_CGL

# This function creates a directory in /tmp owned by the
# current user for the purpose of holding the fifo to
# the user's running copy of CmdlineGL
#
spawn_cgl() {
	[ ! -d $CGL_DIR ] && { mkdir $CGL_DIR; chmod 700 $CGL_DIR; }
	[ ! -e $CGL_DIR/fifo ] && mkfifo $CGL_DIR/fifo
	( ( touch $CGL_DIR/running && CmdlineGL --nouimsg <$CGL_DIR/fifo; rm -f $CGL_DIR/running ) & ) &
}

# If CMDLINEGL_PIPE is defined, use that.
# Otherwise write to the pipe in /tmp, and create it if it doesn't exist.
#
if [ "z$CMDLINEGL_PIPE" != "z" ]; then
	Target="$CMDLINEGL_PIPE"
else
	if [ ! -f $CGL_DIR/running ]; then
		spawn_cgl;
		sleep 1.5;
		if [ ! -f $CGL_DIR/running ]; then
			echo "Failed to start CmdlineGL"
			exit -1
		fi
	fi

	Target=$CGL_DIR/fifo
fi

# Peel off any path from $0 and then send that and its args to the fifo
#
echo `expr "$0" : '.*/\([^/]*\)'` $@ >>$Target
