all: build

build: bin/CmdlineGL ShellBindings bin/CmdlineGL_BashBindings

bin/CmdlineGL: SymbolHash.o Server.o ProcessInput.o ParseGL.o Global.o bin Contained_RBTree.o IntConstHash.autogen.o CmdHash.autogen.o
	gcc -o bin/CmdlineGL -lGL -lGLU -lglut SymbolHash.o Server.o ProcessInput.o Global.o ParseGL.o Contained_RBTree.o IntConstHash.autogen.o CmdHash.autogen.o

ShellBindings: bin CmdlineGLClient *.h
	chmod a+rx CmdlineGLClient \
	&& sed -rn '/^PUBLISHED\(([^,]*),.*/s//\1/p' *.h \
	 | while read fn; do ln -f CmdlineGLClient bin/$$fn; done

bin/CmdlineGL_BashBindings: bin *.h
	sed -rn '/^PUBLISHED\(([^,]*),.*/s//\1/p' *.h \
	 | while read fn; do echo "$$fn() { echo \"$$fn \$$@\"; }"; done > bin/CmdlineGL_BashBindings

Server.o: Server.c Server.h Global.h
	gcc -c Server.c

ParseGL.o: ParseGL.c ParseGL.h Global.h
	gcc -c ParseGL.c

Global.o: Global.c Global.h
	gcc -c Global.c
	
ProcessInput.o: ProcessInput.c ProcessInput.h Global.h ParseGL.h
	gcc -c ProcessInput.c

HashFunc.o: HashFunc.c
	gcc -c -O2 HashFunc.c

SymbolHash.o: SymbolHash.h SymbolHash.c HashFunc.o Global.h
	gcc -c SymbolHash.c

Contained_RBTree.o: Contained_RBTree.c Contained_RBTree.h Global.h
	gcc -c Contained_RBTree.c

IntConstHash.autogen.o: IntConstHash.autogen.c
	gcc -c IntConstHash.autogen.c

IntConstHash.autogen.c: HashTableGenUtil ConstList.txt SymbolHash.h Makefile
	echo "// This code automatically generated by makefile.  Do not modify." > IntConstHash.autogen.c
	echo "#include <GL/gl.h>" >> IntConstHash.autogen.c
	echo "#include <GL/glu.h>" >> IntConstHash.autogen.c
	echo "#include <GL/glut.h>" >> IntConstHash.autogen.c
	echo "#include \"SymbolHash.h\"" >> IntConstHash.autogen.c
	sed -r 's/(GL([^ 	]+))/\2 (int)(\1)/' < ConstList.txt \
	 | ./HashTableGenUtil 1024 IntConstLookup IB IntConstHashEntry >> IntConstHash.autogen.c \
	 || rm IntConstHash.autogen.c

CmdHash.autogen.o: CmdHash.autogen.c
	gcc -c CmdHash.autogen.c

CmdHash.autogen.c: HashTableGenUtil Server.h ParseGL.h SymbolHash.h Makefile
	echo "// This code automatically generated by makefile.  Do not modify." > CmdHash.autogen.c
	echo "#include \"Server.h\"" >> CmdHash.autogen.c
	echo "#include \"ParseGL.h\"" >> CmdHash.autogen.c
	echo "#include \"SymbolHash.h\"" >> CmdHash.autogen.c
	sed -rn '/^PUBLISHED\(([^,]*),([^)]*)\).*/s//\1 \2/p' *.h \
 	 | ./HashTableGenUtil 64 CmdLookup CB CmdHashEntry >> CmdHash.autogen.c \
	 || rm CmdHash.autogen.c

HashTableGenUtil: HashTableGenUtil.c HashFunc.c
	gcc -o HashTableGenUtil HashTableGenUtil.c

ConstList.txt: /usr/include/GL/gl.h /usr/include/GL/glu.h /usr/include/GL/glut.h
	grep "#define" /usr/include/GL/gl.h /usr/include/GL/glu.h /usr/include/GL/glut.h \
	 | sed -r -n 's/^.*#define[ 	]+(GL[^ 	]+).*/\1/p' \
	 > ConstList_new.txt
	echo
	echo ConstList_new.txt has been generated
	echo Some constants need to be edited out by hand.
	echo Then, rename to ConstList.txt
	echo

bin:
	mkdir bin

clean:
	rm -f *.autogen.c
	rm -f *.o
	rm -rf bin/
	rm -f HashTableGenUtil
