all: build

build: CmdlineGL ShellBindings CmdlineGL_BashBindings

CmdlineGL: SymbolHash.o Server.o ProcessInput.o ParseGL.o Global.o bin Contained_RBTree.o
	gcc -o bin/CmdlineGL -lGL -lGLU -lglut SymbolHash.o Server.o ProcessInput.o Global.o ParseGL.o Contained_RBTree.o HashFunc.o

ShellBindings: bin CmdlineGLClient *.h
	chmod a+rx CmdlineGLClient \
	&& sed -rn '/^PUBLISHED\(([^,]*),.*/s//\1/p' *.h \
	 | while read fn; do ln -f CmdlineGLClient bin/$$fn; done

CmdlineGL_BashBindings: bin *.h
	sed -rn '/^PUBLISHED\(([^,]*),.*/s//\1/p' *.h \
	 | while read fn; do echo "$$fn() { echo \"$$fn \$$@\"; }"; done > bin/CmdlineGL_BashBindings

Server.o: Server.c Server.h Global.h
	gcc -c Server.c

ParseGL.o: ParseGL.c ParseGL.h Global.h
	gcc -c ParseGL.c

Global.o: Global.h
	gcc -c Global.c
	
ProcessInput.o: ProcessInput.c ProcessInput.h Global.h ParseGL.h
	gcc -c ProcessInput.c

HashFunc.o: HashFunc.c
	gcc -c HashFunc.c

SymbolHash.o: SymbolHash.h SymbolHash.c CmdHash.autogen.c IntConstHash.autogen.c
	gcc -c SymbolHash.c

Contained_RBTree.o: Contained_RBTree.c Contained_RBTree.h Global.h
	gcc -c Contained_RBTree.c

IntConstHash.autogen.c: HashTableGen.class ConstList.txt Makefile
	echo "// This code automatically generated by makefile.  Do not modify." > IntConstHash.autogen.c;
	sed -r 's/(GL([^ 	]+))/DATA \2 (int)(\1)/' < ConstList.txt \
	 | java HashTableGen 1024 IntConstLookup CnsBucket 'IntConstHashEntry' >> IntConstHash.autogen.c \
	 || rm IntConstHash.autogen.c

CmdHash.autogen.c: HashTableGen.class *.h Makefile
	echo "// This code automatically generated by makefile.  Do not modify." > CmdHash.autogen.c;
	sed -rn '/^PUBLISHED\(([^,]*),([^)]*)\).*/s//DATA \1 \2/p' *.h \
 	 | java HashTableGen 64 CmdLookup CmdBucket 'CmdHashEntry' >> CmdHash.autogen.c \
	 || rm CmdHash.autogen.c

HashTableGen.class: HashTableGen.java
	javac HashTableGen.java

GLConstList.txt: /usr/include/GL/gl.h /usr/include/GL/glu.h /usr/include/GL/glut.h
	grep "#define" /usr/include/GL/gl.h /usr/include/GL/glu.h /usr/include/GL/glut.h \
	 | sed -r -n 's/^.*#define[ 	]+(GL[^ 	]+).*/\1/p' \
	 > GLConstList.txt

bin:
	mkdir bin

clean:
	rm *.autogen.c
	rm *.class
	rm *.o
	rm bin/*

